# Generated by Django 4.2.23 on 2025-08-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_en', models.CharField(max_length=100)),
                ('username_gu', models.CharField(max_length=100)),
            ],
        ),
    ]
